version: '3'
services:
  web:
    build: .
    command: rails s -b 0.0.0.0
    container_name: workshop_subscription
    ports:
      - 3000:3000
    volumes:
      - .:/workshop
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - workshop_subscription:/var/lib/postgresql/data
volumes:
  workshop_subscription:
