default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "workshop") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "workshop") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  timeout: 5000

development:
  <<: *default
  database: workshop_development

test:
  <<: *default
  database: workshop_test

production:
  <<: *default
  database: workshop_production
